app/webapp/blog/models.py
from .. import db


tags = db.Table(
    'post_tags',
    db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
)


class User(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    username = db.Column(db.String(255))
    password = db.Column(db.String(255))
    posts = db.relationship('Post', backref='user', lazy='dynamic')

    def __init__(self, username=""):
        self.username = username

    def __repr__(self):
        return '<User {}>'.format(self.username)


class Post(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    title = db.Column(db.String(255))
    text = db.Column(db.Text())
    publish_date = db.Column(db.DateTime())
    user_id = db.Column(db.Integer(), db.ForeignKey('user.id'))
    comments = db.relationship(
        'Comment',
        backref='post',
        lazy='dynamic'
    )
    tags = db.relationship(
        'Tag',
        secondary=tags,
        backref=db.backref('posts', lazy='dynamic')
    )

    def __init__(self, title=""):
        self.title = title

    def __repr__(self):
        return "<Post '{}'>".format(self.title)


class Comment(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(255))
    text = db.Column(db.Text())
    date = db.Column(db.DateTime())
    post_id = db.Column(db.Integer(), db.ForeignKey('post.id'))

    def __repr__(self):
        return "<Comment '{}'>".format(self.text[:15])


class Tag(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    title = db.Column(db.String(255))

    def __init__(self, title=""):
        self.title = title

    def __repr__(self):
        return "<Tag '{}'>".format(self.title)

app/webapp/blog/forms.py
from flask_wtf import FlaskForm as Form
from wtforms import StringField, TextAreaField
from wtforms.validators import DataRequired, Length


class CommentForm(Form):
    name = StringField(
        'Name',
        validators=[DataRequired(), Length(max=255)]
    )
    text = TextAreaField(u'Comment', validators=[DataRequired()])

app/main.py
import os
from webapp import create_app

env = os.environ.get('WEBAPP_ENV', 'dev')
app = create_app('config.%sConfig' % env.capitalize())


if __name__ == '__main__':
    app.run()

app/webapp/__init__.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

db = SQLAlchemy()
migrate = Migrate()


def page_not_found(error):
    return render_template('404.html'), 404


def create_app(object_name):
    """
    An flask application factory, as explained here:
    http://flask.pocoo.org/docs/patterns/appfactories/

    Arguments:
        object_name: the python path of the config object,
                     e.g. project.config.ProdConfig
    """
    from .blog.controllers import blog_blueprint
    from .main.controllers import main_blueprint

    app = Flask(__name__)
    app.config.from_object(object_name)

    db.init_app(app)
    migrate.init_app(app, db)
    app.register_blueprint(main_blueprint)
    app.register_blueprint(blog_blueprint)
    app.register_error_handler(404, page_not_found)
    return app

app/webapp/blog/controllers.py
from sqlalchemy import func
from flask import render_template, Blueprint, flash, redirect, url_for, current_app
from .models import db, Post, Tag, Comment, User, tags
from .forms import CommentForm

blog_blueprint = Blueprint(
    'blog',
    __name__,
    template_folder='../templates/blog',
    url_prefix="/blog"
)


def sidebar_data():
    recent = Post.query.order_by(Post.publish_date.desc()).limit(5).all()
    top_tags = db.session.query(
        Tag, func.count(tags.c.post_id).label('total')
    ).join(tags).group_by(Tag).order_by('total DESC').limit(5).all()

    return recent, top_tags


@blog_blueprint.route('/')
@blog_blueprint.route('/<int:page>')
def home(page=1):
    posts = Post.query.order_by(Post.publish_date.desc()).paginate(page,
                                                                   current_app.config.get('POSTS_PER_PAGE', 10),
                                                                   False)
    recent, top_tags = sidebar_data()

    return render_template(
        'home.html',
        posts=posts,
        recent=recent,
        top_tags=top_tags
    )


@blog_blueprint.route('/post/<int:post_id>', methods=('GET', 'POST'))
def post(post_id):
    form = CommentForm()

    if form.validate_on_submit():
        new_comment = Comment()
        new_comment.name = form.name.data
        new_comment.text = form.text.data
        new_comment.post_id = post_id
        try:
            db.session.add(new_comment)
            db.session.commit()
        except Exception as e:
            flash('Error adding your comment: %s' % str(e), 'error')
            db.session.rollback()
        else:
            flash('Comment added', 'info')
        return redirect(url_for('blog.post', post_id=post_id))

    post = Post.query.get_or_404(post_id)
    tags = post.tags
    comments = post.comments.order_by(Comment.date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template(
        'post.html',
        post=post,
        tags=tags,
        comments=comments,
        recent=recent,
        top_tags=top_tags,
        form=form
    )


@blog_blueprint.route('/tag/<string:tag_name>')
def posts_by_tag(tag_name):
    tag = Tag.query.filter_by(title=tag_name).first_or_404()
    posts = tag.posts.order_by(Post.publish_date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template(
        'tag.html',
        tag=tag,
        posts=posts,
        recent=recent,
        top_tags=top_tags
    )


@blog_blueprint.route('/user/<string:username>')
def posts_by_user(username):
    user = User.query.filter_by(username=username).first_or_404()
    posts = user.posts.order_by(Post.publish_date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template(
        'user.html',
        user=user,
        posts=posts,
        recent=recent,
        top_tags=top_tags
    )

app/webapp/main/controllers.py
from flask import Blueprint, redirect, url_for, render_template

main_blueprint = Blueprint(
    'main',
    __name__,
    template_folder='../templates/main'
)


@main_blueprint.route('/')
def index():
    return redirect(url_for('blog.home'))

app/templates/blog/head.html
<div class="container bg-info rounded">
    <center>
    <i class="fas fa-comments fa-5x"></i>
    <h1><a class="text-white" href="{{ url_for('blog.home') }}">My Blog</a></h1>
    <p>Welcome to the blog!</p>
    </center>
</div>

app/templates/blog/home.html
{% extends "base.html" %}
{% import 'macros.html' as macros %}
{% block title %}Home{% endblock %}
{% block leftbody %}

{{ macros.render_posts(posts) }}
{{ macros.render_pagination(posts, 'blog.home') }}
{% endblock %}

app/templates/blog/messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{ category }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}

app/templates/blog/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{url_for('blog.home')}}">Home <span class="sr-only">(current)</span></a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('blog.home')}}"></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                <i class="fa fa-fw fa-sign-out"></i>Logout</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                <i class="fa fa-fw fa-sign-in"></i>Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                <i class="fa fa-fw fa-sign-in"></i>Register</a>
            </li>
        </ul>
    </div>
</nav>

app/templates/blog/post.html
{% extends "base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block leftbody %}
<div class="p-4 shadow-sm">
    <div class="row">
        <div class="col">
            <h1>{{ post.title }}</h1>
        </div>
    </div>
    <div class="row shadow-sm">
        <div class="col-lg-6">
            <p>Written By <a href="{{ url_for('posts_by_user', username=post.user.username) }}">{{ post.user.username }}</a> on {{ post.publish_date }}</p>
        </div>
        <div class="col-lg-6">
            <p class="text-right"> Tags: {% for tag in tags %}
                    <a href="{{ url_for('posts_by_tag', tag_name=tag.title) }}">{{tag.title}}</a>
                {% endfor %}
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col">
            {{ post.text | safe }}
        </div>
    </div>
</div>
<div class="p-4 shadow-sm">
    <div class="row">
        <div class="col">
            <h4>New Comment:</h4>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form method="POST" action="{{ url_for('post', post_id=post.id) }}">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.name.label }}
                    {% if form.name.errors %}
                        {% for e in form.name.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.name(class_='form-control') }}
                </div>
                <div class="form-group">
                    {{ form.text.label }}
                    {% if form.text.errors %}
                        {% for e in form.text.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.text(class_='form-control') }}
                </div>
                <input class="btn btn-primary" type="submit" value="Add Comment">
            </form>
        </div>
    </div>
</div>
<div class="p-4 shadow-sm">
    <div class="row">
        <div class="col">
            <h4>Comments ({{ comments | length }})</h4>
        </div>
    </div>
    <div class="row p-2">
        <div class="col">
            {% if comments | length == 0 %}
            <p>There are no comments for this post.</p>
            {% else %}
                {% for comment in comments %}
                <div class="shadow-sm p-2">
                    <dt>By: {{ comment.name }} on {{ comment.date }}</dt>
                    <dd>{{ comment.text }}</dd>
                </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/blog/rightbody.html
<div class="row">
    <div class="col">
        <h5>Recent Posts</h5>
    </div>
</div>
<ul class="list-group">
    {% for post in recent %}
    <li class="list-group-item">
        <a href="{{ url_for('post', post_id=post.id) }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>
<div class="row">
    <div class="col">
        <h5>Popular Tags</h5>
    </div>
</div>
<ul class="list-group">
    {% for tag in top_tags %}
    <li class="list-group-item"
    ><a href="{{ url_for('posts_by_tag', tag_name=tag[0].title) }}">{{ tag[0].title }}</a>
    </li>
    {% endfor %}
</ul>

app/templates/blog/tag.html
{% extends "base.html" %}
{% import 'macros.html' as macros %}
{% block title %}{{ tag.title }}{% endblock %}
{% block leftbody %}
<div class="row">
    <div class="col bg-light">
        <h1 class="text-center">Posts With Tag {{ tag.title }}</h1>
    </div>
</div>
{{ macros.render_posts(posts, pagination=False) }}
{% endblock %}

app/templates/blog/user.html
{% extends "base.html" %}
{% import 'macros.html' as macros %}

{% block title %}{{ user.username }}'s Posts{% endblock %}
{% block leftbody %}
<div class="row">
    <div class="col bg-light">
        <h1 class="text-center">Posts By {{ user.username }}</h1>
    </div>
</div>
{{ macros.render_posts(posts, pagination=False) }}

{% endblock %}

app/templates/head.html
<div class="container bg-info rounded">
    <center>
    <i class="fas fa-comments fa-5x"></i>
    <h1><a class="text-white" href="{{ url_for('home') }}">My Blog</a></h1>
    <p>Welcome to the blog!</p>
    </center>
</div>

app/templates/home.html
{% extends "base.html" %}
{% import 'macros.html' as macros %}
{% block title %}Home{% endblock %}
{% block leftbody %}

{{ macros.render_posts(posts) }}
{{ macros.render_pagination(posts, 'home') }}
{% endblock %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{url_for('home')}}">Home <span class="sr-only">(current)</span></a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('home')}}"></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                <i class="fa fa-fw fa-sign-out"></i>Logout</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                <i class="fa fa-fw fa-sign-in"></i>Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                <i class="fa fa-fw fa-sign-in"></i>Register</a>
            </li>
        </ul>
    </div>
</nav>

app/webapp/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>{% block title %}Blog{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
</head>
<body>
{% include 'navbar.html' %}
<div class="container">
    <div class="row row-lg-4">
        <div class="col">
            {% block head %}
            {% include 'head.html' %}
            {% endblock %}
        </div>
    </div>
    {% include 'messages.html' %}
    {% block body %}
    <div class="row">
        <div class="col-lg-9">
            {% block leftbody %}
            {% endblock %}
        </div>
        <div class="col-lg-3 rounded">
            {% block rightbody %}
            {% include 'rightbody.html' %}
            {% endblock %}
        </div>
    </div>
    {% endblock %}
    {% include 'footer.html' %}
</div>
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>    </body>
</html>

app/webapp/templates/blog/home.html
{% extends "base.html" %}
{% import 'macros.html' as macros %}
{% block title %}Home{% endblock %}
{% block leftbody %}

{{ macros.render_posts(posts) }}
{{ macros.render_pagination(posts, 'blog.home') }}
{% endblock %}

app/webapp/templates/blog/post.html
{% extends "base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block leftbody %}
<div class="p-4 shadow-sm">
    <div class="row">
        <div class="col">
            <h1>{{ post.title }}</h1>
        </div>
    </div>
    <div class="row shadow-sm">
        <div class="col-lg-6">
            <p>Written By <a href="{{ url_for('blog.posts_by_user', username=post.user.username) }}">{{ post.user.username }}</a> on {{ post.publish_date }}</p>
        </div>
        <div class="col-lg-6">
            <p class="text-right"> Tags: {% for tag in tags %}
                <a href="{{ url_for('blog.posts_by_tag', tag_name=tag.title) }}">{{tag.title}}</a>
                {% endfor %}
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col">
            {{ post.text | safe }}
        </div>
    </div>
</div>
<div class="p-4 shadow-sm">
    <div class="row">
        <div class="col">
            <h4>New Comment:</h4>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form method="POST" action="{{ url_for('blog.post', post_id=post.id) }}">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.name.label }}
                    {% if form.name.errors %}
                    {% for e in form.name.errors %}
                    <p class="help-block">{{ e }}</p>
                    {% endfor %}
                    {% endif %}
                    {{ form.name(class_='form-control') }}
                </div>
                <div class="form-group">
                    {{ form.text.label }}
                    {% if form.text.errors %}
                    {% for e in form.text.errors %}
                    <p class="help-block">{{ e }}</p>
                    {% endfor %}
                    {% endif %}
                    {{ form.text(class_='form-control') }}
                </div>
                <input class="btn btn-primary" type="submit" value="Add Comment">
            </form>
        </div>
    </div>
</div>
<div class="p-4 shadow-sm">
    <div class="row">
        <div class="col">
            <h4>Comments ({{ comments | length }})</h4>
        </div>
    </div>
    <div class="row p-2">
        <div class="col">
            {% if comments | length == 0 %}
            <p>There are no comments for this post.</p>
            {% else %}
            {% for comment in comments %}
            <div class="shadow-sm p-2">
                <dt>By: {{ comment.name }} on {{ comment.date }}</dt>
                <dd>{{ comment.text }}</dd>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/webapp/templates/blog/rightbody.html
<div class="row">
    <div class="col">
        <h5>Recent Posts</h5>
    </div>
</div>
<ul class="list-group">
    {% for post in recent %}
    <li class="list-group-item">
        <a href="{{ url_for('blog.post', post_id=post.id) }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>
<div class="row">
    <div class="col">
        <h5>Popular Tags</h5>
    </div>
</div>
<ul class="list-group">
    {% for tag in top_tags %}
    <li class="list-group-item"
    ><a href="{{ url_for('blog.posts_by_tag', tag_name=tag[0].title) }}">{{ tag[0].title }}</a>
    </li>
    {% endfor %}
</ul>

app/webapp/templates/blog/tag.html
{% extends "base.html" %}
{% import 'macros.html' as macros %}

{% block title %}{{ tag.title }}{% endblock %}
{% block leftbody %}
<div class="row">
    <div class="col bg-light">
        <h1 class="text-center">Posts With Tag {{ tag.title }}</h1>
    </div>
</div>
{{ macros.render_posts(posts, pagination=False) }}

{% endblock %}

app/webapp/templates/blog/user.html
{% extends "base.html" %}
{% import 'macros.html' as macros %}

{% block title %}{{ user.username }}'s Posts{% endblock %}
{% block leftbody %}
<div class="row">
    <div class="col bg-light">
        <h1 class="text-center">Posts By {{ user.username }}</h1>
    </div>
</div>
{{ macros.render_posts(posts, pagination=False) }}

{% endblock %}

app/webapp/templates/footer.html
<div class="row">
    Hands on Web development with Flask - 2018
</div>

app/webapp/templates/head.html
<div class="container bg-info rounded">
    <center>
    <i class="fas fa-comments fa-5x"></i>
    <h1><a class="text-white" href="{{ url_for('blog.home') }}">My Blog</a></h1>
    <p>Welcome to the blog!</p>
    </center>
</div>

app/webapp/templates/macros.html
{% macro render_pagination(pagination, endpoint) %}
<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if pagination.has_prev %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('blog.home', page=pagination.prev().page) }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        {% endif %}
        {% for page in pagination.iter_pages() %}
        {% if page %}
        {% if page != pagination.page %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for(endpoint, page=page) }}">{{ page }}</a>
        </li>
        {% else %}
        <li class="page-item active">
            <a class="page-link" href="">{{ page }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="page-item">
            <a class="page-link">…</a>
        <li>
            {% endif %}
            {% endfor %}
            {% if pagination.has_next %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('blog.home', page=pagination.next().page) }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endmacro %}

{% macro render_posts(posts, pagination=True) %}
{% if pagination %}
{% set _posts = posts.items %}
{% else %}
{% set _posts = posts %}
{% endif %}

{% for post in _posts %}
<div >
    <h1>
        <a class="text-dark" href="{{ url_for('blog.post', post_id=post.id) }}">{{ post.title }}</a>
    </h1>
</div>
<div class="row">
    <div class="col">
        {{ post.text | truncate(500) | safe }}
        <a href="{{ url_for('blog.post', post_id=post.id) }}">Read More</a>
    </div>
</div>
{% endfor %}
{% endmacro %}

app/webapp/templates/messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{ category }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}

app/webapp/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{url_for('blog.home')}}">Home <span class="sr-only">(current)</span></a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('blog.home')}}"></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                <i class="fa fa-fw fa-sign-out"></i>Logout</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                <i class="fa fa-fw fa-sign-in"></i>Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                <i class="fa fa-fw fa-sign-in"></i>Register</a>
            </li>
        </ul>
    </div>
</nav>